### ISSUE TITLE
An argument to compile Lua

### ISSUE THREAD

**Issue by qaisjp** [leafo/moonscript#115]
It would be nice if we could add a "--lua_compile" or "--compile" flag to compile the lua script automatically.

Just as a side question, afaik compiling increases load speed right? Does it make a significant speedup? I slowly see my load time increasing, but I suspect that is because I am generating all the HTML instead of storing some of it raw.

**Comment by hydroper** [comment]
I find it interesting that compiling to .luac allows for debugging, which is useful for source maps.
