### ISSUE TITLE
watch errors: "Missing sleep function; install LuaSocket"

### ISSUE THREAD

**Issue by mationai** [leafo/moonscript#135]
moonc file.moon works, but when running moonc -w, it errors asking me to install luasocket. After installing it via "luarocks install luasocket", it still errors:

> moonc -w .
> /usr/local/bin/lua: /usr/local/lib/luarocks/rocks/moonscript/dev-1/bin/moonc:282: Missing sleep function; install LuaSocket
> stack traceback:
>     [C]: in function 'error'
>     /usr/local/lib/luarocks/rocks/moonscript/dev-1/bin/moonc:282: in function 'get_sleep_func'
>     /usr/local/lib/luarocks/rocks/moonscript/dev-1/bin/moonc:337: in function 'create_watcher'
>     /usr/local/lib/luarocks/rocks/moonscript/dev-1/bin/moonc:363: in main chunk
>     [C]: in ?

**Comment by italomaia** [comment]
I have the same error. Reinstall did not work and ``lua -e 'require("socket")' works

**Comment by nucleartide** [comment]
I submitted a PR awhile back that fixed this issue ([link](https://github.com/leafo/moonscript/pull/160)). It seems like MoonRocks has a version of moonscript without the fix though. You could always edit that file directly. :)

**Comment by rjhilgefort** [comment]
Why not just `luarocks install luasocket` to make sure you have it?
