### ISSUE TITLE
Strange behavior of `to_lua` with LPeg 0.12

### ISSUE THREAD

**Issue by shmuz** [leafo/moonscript#150]
[Windows XP SP3, MinGW, Lua 5.1, MoonScript 0.2.6]
**The following test behaves OK with LPeg 0.10.2 but throws an error with LPeg 0.12**
```
local to_lua = require("moonscript.base").to_lua
local function test()
  local t = os.clock()
  for k=1,50 do to_lua("5") end
  io.write(os.clock() - t, " ")
end
for k=1,5 do test() end
```
**Output with LPeg 0.10.2:**
```
0.156 0.157 0.156 0.156 0.156
```
**Output with LPeg 0.12:**
```
0.375 0.625 0.86 C:\Exe32\lua.EXE: s:/lua_share/moonscript\parse.lua:364:
rule '(a function)' undefined in given grammar
stack traceback:
        [C]: in function 'P'
        s:/lua_share/moonscript\parse.lua:364: in function 'build_grammar'
        s:/lua_share/moonscript\parse.lua:635: in function 'string'
        s:/lua_share/moonscript\base.lua:38: in function 'to_lua'
        test1.lua:4: in function 'test'
        test1.lua:7: in main chunk
        [C]: ?
```

**Comment by leafo** [comment]
Sorry for not responding. This has been a known issue for quite some time. It looks like the culprit is related to how the parser automatically generate non-terminals: http://lua-users.org/lists/lua-l/2015-02/msg00035.html

**Comment by zg0** [comment]
possible that this is not moonscript related problem. here http://lua-users.org/lists/lua-l/2015-02/msg00352.html I provided testcase without moonscript.

**Comment by leafo** [comment]
Thanks for taking the time to look into it

**Comment by leafo** [comment]
removing the cache for lpeg.V seems to fix all instance where I could reproduce problem.

**Comment by zg0** [comment]
eats ktable entries slowly, but stil crashes after ~7200 calls:

local to_lua = require("moonscript.parse").string
local function test(iteration)
  local t = os.clock()
  for k=1,50 do to_lua("5") end
  io.write(iteration,":",os.clock() - t, " ")
end
for k=1,200 do test(k) end

for me its only lpeg problem.

**Comment by leafo** [comment]
I agree it's an lpeg problem, but I should do the best I can to mitigate it until it's fixed.

**Comment by zg0** [comment]
with 0.12.2 0.2.6 and 0.3.0 versions works fine.

**Comment by leafo** [comment]
great news :)
