### ISSUE TITLE
moon-watch, a little shell script for better moonc --watch, might be helpful

### ISSUE THREAD

**Issue by yi** [leafo/moonscript#152]
We are working on lua project by using moonscript, and I found the moonc -w is a bit weak on MacOS. I read on the moonscript website, that using a filesystem watcher tool might be a better idea. 

So I wrote a little piece of shell script, and made it a moon-rock package. We now have a moonscript watcher works more like `coffee -w`. 

Here is the package, I think it might be helpful to you guys. 

https://rocks.moonscript.org/modules/yi/moon-watch

**Comment by ChickenNuggers** [comment]
The MoonScript watching mechanism attempts to provide compatibility with whatever environment the user is in; if the user has libraries that are better suited, those libraries are used by the watcher. Thanks for posting this anyways, but do you mind closing the issue?

**Comment by yi** [comment]
thansk. issue closed
