### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by gelnior** [leafo/moonscript#162]
Hello,

On Ubuntu 14.04, I installed Lua 5.2 and luarocks via apt-get. After installing Moonscript via luarocks, I run into the following error when I use the `moonc` command:

```
/usr/bin/lua: /usr/share/lua/5.1//luarocks/loader.lua:113: error loading module 'lfs' from file '/usr/local/lib/lua/5.1/lfs.so':
	/usr/local/lib/lua/5.1/lfs.so: undefined symbol: luaL_register
stack traceback:
	[C]: in function 'loader'
	/usr/share/lua/5.1//luarocks/loader.lua:113: in function </usr/share/lua/5.1//luarocks/loader.lua:110>
	(...tail calls...)
	[C]: in function 'require'
	/usr/local/lib/luarocks/
```

Do you have any idea of what I did wrong?

I like coding in Coffeescript, so I think Moonscript is a great idea for Lua.

**Comment by andyl** [comment]
I have the same problem.

**Comment by suchipi** [comment]
Make sure you are using the lua5.1 package instead of the lua5.2 package. Try:
```command
sudo apt-get install lua5.1
sudo apt-get remove lua5.2
```

You should see a message from `update-alternatives` noting that it will use `lua5.1` and `luac5.1`.

**Comment by gelnior** [comment]
Ok. Thank you @suchipi.

**Comment by pabloriutort** [comment]
Had the same problem. Good solution.

**Comment by ErikUggeldahl** [comment]
Same here, with a slightly different error:

```
/usr/bin/lua: /usr/share/lua/5.1//luarocks/loader.lua:113: error loading module 'lpeg' from file '/usr/local/lib/lua/5.1/lpeg.so':
	/usr/local/lib/lua/5.1/lpeg.so: undefined symbol: lua_tointeger
```

Thanks for the fix.

**Comment by leafo** [comment]
MoonScript should work fine on all versions of Lua. It seems like there's a luarocks environment problem, it's trying to use modules compiled for another version of Lua.
