### ISSUE TITLE
moonc always dumps compiled files in the source dir, even with -t

### ISSUE THREAD

**Issue by dhasenan** [leafo/moonscript#169]
$ ls ../Scripts
    bar.moon foo.moon
    $ moonc -t . ../Scripts/*.moon
    $ ls
    bar.lua foo.lua
    $ ls ../Scripts
    bar.lua bar.moon foo.lua foo.moon

`-t` apparently just compiles the files and outputs them like normal, then copies them to the output directory. It should not. Using latest git master.

**Comment by leafo** [comment]
Sorry, some flags were disabled with a refactor. Fixed in master now. New version coming out shortly
