### ISSUE TITLE
MoonScript 0.3.0 parser enters an inconsistent state after an unsuccessful chunk parsing

### ISSUE THREAD

**Issue by shmuz** [leafo/moonscript#177]
Running the following code
```
to_lua = require("moonscript.base").to_lua
to_lua "{b=5}"
to_lua "{b=5}"
```
produces the following error:
> moon: [string "moonscript.lua"]:2854: attempt to call upvalue 'pos' (a number value)
stack traceback:
        [string "moonscript.lua"]:2854: in function 'build_grammar'
        [string "moonscript.lua"]:2975: in function 'string'
        [string "moonscript.lua"]:390: in function 'to_lua'
        2.moon:3: (3) in main chunk

while I was expecting just returning ``nil``.

**Comment by szensk** [comment]
@leafo line 334 in parse.moon should be `local pos = last_pos` if I understand correctly

**Comment by leafo** [comment]
Thanks, will push out 0.3.1 in a bit.
