### ISSUE TITLE
Question regarding middleclass

### ISSUE THREAD

**Issue by kernelsauce** [leafo/moonscript#182]
Hi. I am maintaining a library largely based on the Middleclass class library. What is the shortest route to make it compatible with the class system in Moonscript without rewriting in Moonscript?

**Comment by leafo** [comment]
I'm not familiar with middleclass but you could implement a intermediate class in moonscript that proxies to a middle class. I'm assuming so this is so you can write a moonscript class extending a middle class?

You can see the interface classes expect for inheritance by looking at the generated Lua code http://moonscript.org/reference/#inheritance

**Comment by kernelsauce** [comment]
Yes, that is correct. Inheritance is required for this. I will look at the
inheritance ref.

2015-04-02 9:00 GMT+02:00 leaf <notifications@github.com>:

> I'm not familiar with middleclass but you could implement a intermediate
> class in moonscript that proxies to a middle class. I'm assuming so this is
> so you can write a moonscript class extending a middle class?
>
> You can see the interface classes expect for inheritance by looking at the
> generated Lua code http://moonscript.org/reference/#inheritance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leafo/moonscript/issues/182#issuecomment-88780009>.
>



-- 
Best regards/Vennlig hilsen
John Abrahamsen
Mobile: (+47) 945 40 425

**Comment by ChickenNuggers** [comment]
@kernelsauce can you close this, assuming your issue is resolved?
