### ISSUE TITLE
uninitialized class variable refers main block's variable

### ISSUE THREAD

**Issue by Nymphium** [leafo/moonscript#188]
when declare `x = 1` in main block and set `:x` in a class, the `x` in the class points `x` in MAIN BLOCK.

```moon
x = 1

class Cls
 :x

-- we want this code say "nil" but...
with Cls!
 print .x --> 1
```

the compiled lua code is below:

```lua
local x = 1
local Cls
do
  local _base_0 = {
    x = x
  }
  _base_0.__index = _base_0
  local _class_0 = setmetatable({
.....
```

in the compiled  lua code, `x` in the class variable is declared `x = x`. it will occur a critical probrem, and  I think it's better to declare `x = nil`.

**Comment by Yorwba** [comment]
I don't think you understand what `:x` means. It takes the value of `x` and stores it in the key of the same name. If you want `x` to be `nil`, write `x: nil`.

**Comment by leafo** [comment]
Class bodys work like table literals, see the section about the `:` prefix operator here: http://moonscript.org/reference/#table_literals

**Comment by Nymphium** [comment]
Umm... `tbl = {:x}` means `tbl.x = x`, and the behave I pointed out is working properly, right? If so, I have a terrible misunderstanding. Sorry.
