### ISSUE TITLE
Optional type annotations

### ISSUE THREAD

**Issue by idmit** [leafo/moonscript#189]
First of all, thanks for creating moonscript!

Is there any chance of implementing optional type annotations? Or you want to leave moonscript just as a syntactic sugar extension conceptually?

**Comment by kirbyfan64** [comment]
Type annotations that are actually useful is hard in Lua and company because using `nil` in Lua is considered idiomatic. As a result,  things like undeclared variables aren't necessarily errors; same thing goes for wrong argument count to function call.

**Comment by ludamad** [comment]
I'd personally really like a version of Moonscript with features like TypeScript, but it would probably best a some kind of Moonscript compiler module.

**Comment by rosshadden** [comment]
Perhaps by leveraging something like [Typed Lua](https://github.com/andremm/typedlua)?

Slides with examples [here](https://www.lua.org/wshop14/Murbach.pdf), and his original PhD thesis [here](http://www.lifl.fr/dyla14/papers/dyla14-4-typed-lua-an-optional-type-system.pdf).

**Comment by idmit** [comment]
I don't support this anymore, closing the issue ⭐️

**Comment by idmit** [comment]
@Guard13007 I've come to believe that expressivity > proof. Since opening this issue I've learned Clojure and [clojure.spec](https://clojure.org/about/spec) just felt very-very right (you can learn more about it from this great [talk](https://youtu.be/VNTQ-M_uSo8)).

So the addition of some lightweight type system with annotations to a language like Moonscript started to feel like a lot of effort for a really unclear gain from the developer perspective. I really doubt that a lot of people use languages like Lua or Moonscript for anything performance critical, so these languages should be more concerned with their expressive powers and ease of use than anything else. With this in mind please refer to the above links that explain thoroughly why some tasks (like validation and error reporting) are better handled with something like specs.

All of this comes down to opinions and preferences, so I just hope that I've mentioned something unfamiliar to you even if you'll later decide that it's not that good 😄

**Comment by ludamad** [comment]
Hi. I have increasingly been looking for optional type annotations, I'm not so sure it's a good idea to close this bug. If you've ever used typescript, you'd know the potential gain is really clear (but I would settle for something much simpler and runtime checked). A _lot_ more people use Lua for performance critical things than you seem to believe. I am one of them. I've been a few pain moments away from hacking this onto the moonscript compiler for some time.

**Comment by idmit** [comment]
@ludamad I wouldn't consider this issue a bug 😄 

But anyway, I can reopen it, if there is a need, but I figured that the maintainer is not interested in this. So whether the issue is open or closed doesn't really change much.
