### ISSUE TITLE
Does moonscript support coroutines? Also, any performance penalty against just lua/luajit?

### ISSUE THREAD

**Issue by hwongcom** [leafo/moonscript#195]
Does moonscript support coroutines? Also, any performance penalty against just lua/luajit?

**Comment by deathbeam** [comment]
As MoonScript is language compiled to Lua, it should also have same performance and yes, it supports everything, that your installed version of Lua does.

**Comment by hwongcom** [comment]
Great. Will be using lapis + moonscript then. Thanks.
