### ISSUE TITLE
What ide to use moonscript on?

### ISSUE THREAD

**Issue by hwongcom** [leafo/moonscript#196]
I would like to see moonscript with Netbeans "plugin" or something to easily code moonscript in. what do you normally code moonscript in?

**Comment by deathbeam** [comment]
I am personally using Sublime Text 2 and it is working fine.

**Comment by kirbyfan64** [comment]
I use [Howl](http://howl.io). It's more of a programming text editor than an IDE, but it's fantastic. The MoonScript syntax highlighting never fails, and it starts up much more quickly than Sublime. In fact, Howl is actually written in MoonScript!

**Comment by deathbeam** [comment]
That Howl looks nice. Btw, hello @kirbyfan64, I saw you on Crystal issue tracker too :smile:

**Comment by nonchip** [comment]
sublime text 3. works just fine, and there are packages for lua, moon, and LÖVE-specific autocompletion

**Comment by nonchip** [comment]
metaquestion: why is this even an issue? seems better suited for e.g. stackexchange or the wiki

**Comment by leafo** [comment]
there is no where to have discussion on moonscript so we've been using the issues tracker

**Comment by leafo** [comment]
I'm probalby going to launch a moonscript/lapis community pretty soon with [lapis-community](https://github.com/leafo/lapis-community), but haven't had a chance yet. There's also #moonscript on freenode for irc.

**Comment by edgardmota** [comment]
I know this topic is a little dated, but there are ZeroBrane (http://studio.zerobrane.com/) too, which provides even debugging features. Its syntax highlighting get buggy sometimes and autocomplete doesn't work very well too.

**Comment by leafo** [comment]
I recently released a syntax package for [Textadept](http://foicica.com/textadept/): https://github.com/leafo/moonscript-textadept

Going to close this as there doesn't appear to be any issues.
