### ISSUE TITLE
invalid precedence when passing single arg literal

### ISSUE THREAD

**Issue by leafo** [leafo/moonscript#200]
```moon
m = P[[hello]] / "yeah"
```

compiles to

```lua
local m = P([[hello]] / "yeah")
```

expected:

```lua
local m = P([[hello]]) / "yeah"
```

**Comment by stevedonovan** [comment]
I would certainly have expected the first result, so now I'm confused!

There's the special case of string literal following a function without
space which does work as here;  but I am seeing a space here.

**Comment by leafo** [comment]
I made a typo when I first wrote the issue, you're responding from email I guess github emailed you before I made the fix. Check the issue on the site
