### ISSUE TITLE
Something like "interfaces"

### ISSUE THREAD

**Issue by CriztianiX** [leafo/moonscript#212]
are there plans to implements "interface" concept? Something like this library:
https://github.com/bhou/Bo-LuaOOP

**Comment by leafo** [comment]
Probably not from a language level. I think using a library to enhance the class system is the best bet.

**Comment by darmie** [comment]
@leafo can you suggest how once could use a library to enhance the class system. 

I would love to do something like this:

```moonscript
class Bindable extends dependencyObservable.DependencyObservable implements definition.Bindable{

}
```
