### ISSUE TITLE
lpeg error 'Advance is not a pattern'

### ISSUE THREAD

**Issue by thegrb93** [leafo/moonscript#223]
The lpeg library I'm using is giving an error for one of the patterns used in parse.lua
I fixed it by changing parse.lua:116 from

```
Advance = #Cmt(Indent, advance_indent),
```

to

```
Advance = Cmt(Indent, advance_indent),
```

and the error doesn't occur anymore. I don't know if this is right or not, but it seems right.

**Comment by leafo** [comment]
Those parse expressions have two different meanings. What's the lpeg library you're using? (The `#` operator causes the pattern to not consume any text if it matches btw)

**Comment by thegrb93** [comment]
I'm using https://github.com/pygy/LuLPeg
I guess that operator isn't compatible with it?

**Comment by leafo** [comment]
hmm, yeah if I remember correctly that operator couldn't be overloaded in the pure lua version. I can update the grammar to support it though.

**Comment by thegrb93** [comment]
Looks like it does support it, but the lua version I'm using doesn't.

**Comment by thegrb93** [comment]
I found a warning that says "Warning: The `__len` metatethod won't work with patterns, "
            .."use `LL.L(pattern)` for lookaheads."

Does that mean
```
Advance = #Cmt(Indent, advance_indent),
```
needs to be changed to this?
```
Advance = Cmt(Indent, advance_indent):L(),
```

**Comment by thegrb93** [comment]
I tried it out and seems to work. Now I just have to figure out why comments aren't being ignored.

**Comment by thegrb93** [comment]
This is the moonscript
```
--@name 
--@author
--@moonscript

if not SERVER then return

my_function = (name="something", height=100) ->
  print "Hello I am", name
  print "My height is", height
```
This is the result
```
local _ = -self.author
if not SERVER then
  return 
end
local my_function
my_function = function(name, height)
  if name == nil then
    name = "something"
  end
  if height == nil then
    height = 100
  end
  print("Hello I am", name)
  return print("My height is", height)
end
```

**Comment by leafo** [comment]
is it just skipping the first character? what if there are comments in other places in the file?

**Comment by thegrb93** [comment]
```

if not SERVER then return

my_function = (name="something", height=100) ->
  print "Hello I am", name
  print "My height is", height
  
--@name 
--@author 
--@moonscript
```
gives
```
if not SERVER then
  return 
end
local my_function = function(name, height)
  if name == nil then
    name = "something"
  end
  if height == nil then
    height = 100
  end
  print("Hello I am", name)
  return print("My height is", height)
end - self.name
return -self.moonscript
```

```

if not SERVER then return

my_function = (name="something", height=100) ->
  print "Hello I am", name
  print "My height is", height
  
 --@name 
 --@author 
 --@moonscript
```
gives
```
Failed to parse:
 [10] >>    --@moonscript
```

```

if not SERVER then return

--@name 
--@author 
--@moonscript

my_function = (name="something", height=100) ->
  print "Hello I am", name
  print "My height is", height
```
gives
```
if not SERVER then
  return 
end
local _ = -self.author
local --@moonscript

my_function
--@moonscript

my_function = function(name, height)
  if name == nil then
    name = "something"
  end
  if height == nil then
    height = 100
  end
  print("Hello I am", name)
  return print("My height is", height)
end
```

**Comment by leafo** [comment]
I just pushed a patch to allow lulpeg to work with fc77603, you might want to try again

**Comment by leafo** [comment]
Actually it's probably not going to work, having issues getting the test suite to pass with lulpeg

**Comment by thegrb93** [comment]
Works with my test now. Thanks a million.
