### ISSUE TITLE
Multiline arguments in function literals?

### ISSUE THREAD

**Issue by Michael-F-Ellis** [leafo/moonscript#227]
When defining functions with many args and/or long argument names, I'd like to be able to put the arguments on multiple lines.  The following produces a parse error in version 0.4.0-1 :

    func_with_long_args = (a_long_argument_name,
                           another_long_argument_name)  ->

I'm new to moonscript, so I apolgize for adding noise if there's a way to do this that I've not yet found.

**Comment by leafo** [comment]
not possible at the moment, but should be added

**Comment by Michael-F-Ellis** [comment]
Ok and many thanks for creating moonscript.  I'm a long-time Python developer with a need to write a project in Lua.  Moonscript may just save my sanity!
