### ISSUE TITLE
moonc -t doesn't work

### ISSUE THREAD

**Issue by harraps** [leafo/moonscript#228]
I try to create a .bat file to run my love2d project
But it's seams that the -t flag doesn't work
I want to specified a folder for my moon files and an other one for the generated lua files.

I got the following hierarchy:
project_folder:
   src:
      main.moon
      math.moon
   gen:
      main.lua // should be here
      math.lua // should be here too
   run.bat

and my bat contains the following commands

moonc %cd%\src -t %cd%\gen
"I:\Programs\GameEngines\LOVE\love.exe" %~dp0\gen

but the command keep telling me that it cannot find the file "gen"
but it's not supposed to be a file but a directory :/

**Comment by harraps** [comment]
Ok I manage to make the flag -t work
But it could have been easier if there was a way to tell the compiler if a parameter is a file name or a directory...

so here is my new run.bat

moonc -t "gen" "src"
I:\Programs\GameEngines\LOVE\love.exe "gen//src"
PAUSE

it's still create a src directory inside the gen directory
but that's fine it more or less do what I wanted it to do...

**Comment by ChickenNuggers** [comment]
This is the intended purpose; if you want to have a better way to do this, you could instead try this:

```batch
moonc -t "..\gen" .
I:\Programs\GameEngines\LOVE\love.exe "..\gen"
PAUSE
```

Try this and tell us the result.

**Comment by ChickenNuggers** [comment]
@harraps any update on this?

**Comment by harraps** [comment]
Sorry I moved on on other projects I forgot about that issue.
Your solution works fine indeed.
I forgot that "." points to the current directory :/
That's why I had trouble to make it works like I wanted.

I really thank you for your response.

**Comment by ChickenNuggers** [comment]
@harraps Do you mind closing the issue?
