### ISSUE TITLE
Enums?

### ISSUE THREAD

**Issue by eigenbom** [leafo/moonscript#229]
Have you considered implementing enums at all? A handy style could be:

```
Screen = 
  Title
  CharacterSelect
  Playing
  Paused
  Won
  Lost
```

**Comment by leafo** [comment]
What would the values be? I think the lua way of doing things is to typically just use strings, so "Title", "CharacterSelect", etc. All strings are internalized in lua so their comparison is o(1)

**Comment by szensk** [comment]
You can make your own enum type with metatable abuse. [It's less elegant.](https://gist.github.com/szensk/7986347f09742337b36e)

On the other hand, we have :title which does `title = title` already. Why not `title for `title = 'title'`?

**Comment by eigenbom** [comment]
Oh right, I guess I'm in the c++ mindset. I started doing something like this, 

```
Screen =
  Start: 0
  Game: 1
  End: 2
```

Using strings sounds ok to me, it will certainly do the job. Part of me wants the compiler and run-time to know what the valid values are though. There are a tonne of ways to do it I suppose.

```
enum = (n) -> unpack [i for i=1,n]
Start, Game, End = enum 3
screen = Start
switch screen
  when Start
    print "hello"
```

**Comment by eigenbom** [comment]
You can even drop the count if you make enum! return a big enough value ...

```
enum = -> unpack [i for i=1,100]
Start, Game, End = enum!
```

**Comment by leafo** [comment]
if you want some rudimentary type checking then I recommend the metatable approach, you can cause it to throw an error if you ask for a value that isn't known. 

Here's an alternative implementation:

```moonscript
enum = (values) ->
  setmetatable {v,v for v in *values}, __index: (k) =>
    error "don't know `#{k}` for enum"

-- in action:

types = enum {"Character", "Enemy"}

-- reference enum by name
print types.Character --> "Character"

-- verify value is enum:
my_type = types.Character
print types[my_type] --> no error, returns "Character"

-- throw error with bad things
print types.BadThing --> error

my_bad_type = "NotReal"
print types[my_bad_type] --> error
```

**Comment by leafo** [comment]
Also in the above example if you want to export the enums to locals you can just destructure:

```moonscript
{:Character, :Enemy} = types
```

or use import

```moonscript
import Character, Enemy from types
```

**Comment by szensk** [comment]
@leafo That's a much better solution! Thanks for posting it.

**Comment by eigenbom** [comment]
Ok, thanks :+1:
