### ISSUE TITLE
self incorrectly identified as global in class declaration

### ISSUE THREAD

**Issue by kevinw** [leafo/moonscript#230]
The linter successfully flags this:

```lua
class foo
  bar = ->
    print self
```

```
line 43: accessing global `self`
================================
>     print self
```

But it misses the error when you use @:

```lua
class foo
  bar = ->
    print @
```

Forgetting to use a fat arrow in methods is a mistake I'm making just often enough to be annoying, so it'd be nice if the linter helped me out here.

**Comment by leafo** [comment]
hmm interesting, `self` is actually defined there BTW, it's the value of the class:

```moonscript
class Something
  thing = ->
    print @

  thing! --> table: 0x931d38
```

So I think the bug might be that self is incorrectly being identified as a global

**Comment by ChickenNuggers** [comment]
@leafo @kevinw can one of you two change the title to something along the lines of "`self` incorrectly identified as global in class declaration"?

**Comment by leafo** [comment]
can't reproduce this
