### ISSUE TITLE
Is there anyway I can indent code under comments?

### ISSUE THREAD

**Issue by farzher** [leafo/moonscript#235]
This is a weird thing I personally do to group code to comments (in sublime I can even then fold the code related to that comment!)

![](http://i.imgur.com/I554rZJ.png)

But trying to do this in moonscript throws errors. I was able to do this in LiveScript (similar to CoffeeScript) by putting `do` in front of comments

```
do # Spaghetti code
  a=1
  b=2
```

But this causes a scope block in Lua and messes things up. Any ideas?

**Comment by Kingdaro** [comment]
You can use the do block, along with putting `export *` at the beginning of it.

**Comment by farzher** [comment]
```moonscript
export * do -- Spaghetti code
  a=1
  b=2
```

Doesn't compile

**Comment by Kingdaro** [comment]
After the do, I mean. Indented on the next line.

**Comment by farzher** [comment]
Ah, okay I see.
That doesn't actually work though because I want my variables to be local

**Comment by farzher** [comment]
(I showed a bad example picture with only global stuff)
This actually works fine
The issue is when I want local variables, but they get scoped in the `do` block

**Comment by Kingdaro** [comment]
Then don't indent? It's a language paradigm for any indented statement to be a part of that block, and it'd be silly for moonscript to add a way to break that. You can also just put `local var1, var2, ...` above the do to localize any variable you need.

**Comment by ChickenNuggers** [comment]
Do it the C90 way; initialize your variables before the `do` statement. That also helps you recognize what is being initialized inside of the block. Example (kinda like ComputerCraft-style, but you should get the gist of it):

```moonscript
local startX, startY
-- Get start position to center text
do
  maxX, maxY = term.getCursorPos!
  startX, startY = ((maxX-#text)/2), maxY/2
```

**Comment by farzher** [comment]
@ChickenNuggers I really like that concept, it's just a bit too verbose for me...

Is there anyway I can get this to compile? (I tried putting a semicolon before `do`, but I can't get it to compile on 1 line)

```moonscript
local x, y do -- Math things
  a=2
  x=a^3
  y=a*x
```

**Comment by ChickenNuggers** [comment]
In a language as whitespace-based as MoonScript, it's hard to create a
multiline statement that isn't an expression. The best way you're going to
do this is probably to do it in the split-line format.

On Tue, Jan 12, 2016 at 11:11 AM Stephen Kamenar <notifications@github.com>
wrote:

> @ChickenNuggers <https://github.com/ChickenNuggers> I really like that
> concept, it's just a bit too verbose for me...
>
> Is there anyway I can get this to compile? (I tried putting a semicolon
> before do, but I can't get it to compile on 1 line)
>
> local x, y do -- Math things
>   a=2
>   x=a^3
>   y=a*x
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leafo/moonscript/issues/235#issuecomment-170978392>.
>
> Augusta Public Schools USD 402- Student Email

-- 

Charles Heywood <vandor2012@gmail.com>
Programmer :: Scripter :: Designer :: Administrator
https://github.com/ChickenNuggers

**Comment by farzher** [comment]
LiveScript simply lets you use semicolons for newlines

```livescript
i = 0; while i < 10, i++
  dostuff i
  # Semicolon saved me a line, cool!
```

Maybe that's something to consider for moonscript.
Eitherway, this solves my comment indentation issue pretty well, thanks!
