### ISSUE TITLE
Add optional 5.3 compatibility to the parser/lexer (Or: Front-of-file metadata)

### ISSUE THREAD

**Issue by ChickenNuggers** [leafo/moonscript#237]
For features such as vim modelines (`vim: noet colorcolumn=80`) I think it's reasonable to add file metadata that could allow for setting compile-time metadata. This could be useful for things such
as specifying Lua versions, which could fix compatibility between Lua versions (see: #125 and #126).

An example would be:

```moonscript
-- moonc: compat=5.3
band = (x, y)-> x & y
print band(5, 7) == 5
```

**Comment by ChickenNuggers** [comment]
This could also be used as a moonc argument like how `cpp` has `-D<macro[=value]>`.

**Comment by leafo** [comment]
If we did something like this it makes more sense to have a command line flag, not introduce new syntax.

**Comment by ChickenNuggers** [comment]
It's not entirely new syntax, though? It's a comment.

**Comment by ChickenNuggers** [comment]
Plus, command-line flags leaves out support for people who want to make applications in MoonScript but ship them for Lua.

**Comment by leafo** [comment]
It's definitely new syntax. Using a comment on the top of source file is something people who write preprocessors have to resort to when they don't have access to the language that's underneath. I'm not a fan of add adding a in-comment meta-language.

How would embedding the information in the file solve the problem with making MoonScript applications and shipping them for Lua? Wouldn't it be the other way around, the command line flag is where the flexibility is?

**Comment by ChickenNuggers** [comment]
Is there a reason behind not wanting to add "meta-language"? If you don't want it in a comment, you could do it like `export`.

Also, adding it to a file could make for easier compiling (running moonc . instead of moonc -FLAG1 -FLAG2 .).

**Comment by leafo** [comment]
I've pretty much already build the community tools: https://github.com/leafo/lapis-community

Also I much prefer using moonscript to power moonscript related things. I just want to get if people would use it

**Comment by ChickenNuggers** [comment]
I guess there's no real reason for this since symbols were added compatible with 5.3.
