### ISSUE TITLE
Suggest to support Terralang

### ISSUE THREAD

**Issue by wuxianliang** [leafo/moonscript#241]
If Moonscript support [Terralang](http://terralang.org) which is a new low-level system programming language that is designed to interoperate seamlessly with the Lua programming language, we will not worry about performance any more and do meta-programming immediately. I think it worth trying. Thank you.

**Comment by ChickenNuggers** [comment]
This is not likely to be included; attempting to chain preprocessors (I consider MoonScript a preprocessor) is generally not a good idea.

**Comment by wuxianliang** [comment]
Dear @ChickenNuggers 
Thank you for response. I did a further reading on Terralang. There is a terralang library [Quicksand](http://dritchie.github.io/quicksand/index.html) for probabilistic programming, which the author writes in the [paper](http://stanford.edu/~dritchie/qs.pdf)
```
In addition, we would like to see Quicksand embedded in games that use Lua scripting. This could allow game developers and even end-users, given a small amount of extra training, to add complex procedurally-generated content to their virtual worlds.
```
It worth to take a look on his [works](http://stanford.edu/~dritchie/work.html)
I am planning to build a lot with Moonscript and Torch7. So I suggested to power Moonscript further.
At least, I think if we keep Moonscript stable in master branch, would you like to write something about how to develop Moonscript further in other forks. @leafo 
Then I would like to 
```
move fast, not break too much, I hope
```
and we can see if it is good. Please share more knowledge on building Moonscript, Thank you very much!
