### ISSUE TITLE
How to use Gtk (lgi) in moonscript? 

### ISSUE THREAD

**Issue by handicraftsman** [leafo/moonscript#243]
P. S. Don't tell me about gtk.init() and gtk.main() - i already added it without crashes.

**Comment by Kingdaro** [comment]
Post your problematic code? All of it, preferably, and an error message, so we can help you a little better. There shouldn't be anything on Moonscript's side that keeps you from using anything Lua-related.

**Comment by handicraftsman** [comment]
```moonscript
window = ->
  gtk.init()

  class win extends gtk.Window
    title = "Test Moon App"
    default_width = 1024, default_height = 768
    -- class box extends gtk.Box
    --   orientation = gtk.Orientation.HORIZOLTAL

  gtk.main()
```

```
moon: /usr/local/share/lua/5.1/moonscript/base.lua:81: ./win.moon: Failed to parse: left hand expression is not assignable
 [4] >>    class win extends gtk.Window
```
When i am uncommenting gtk.box, it says:
```
moon: /usr/local/share/lua/5.1/moonscript/base.lua:81: ./win.moon: Failed to parse:
 [7] >>    class box extends gtk.Box
```

**Comment by Kingdaro** [comment]
Your problem is with this line:
```moon
default_width = 1024, default_height = 768
```
It should be:
```moon
default_width, default_height = 1024, 768
```

However, it doesn't appear as though using MoonScript's class syntax is the best approach here. A quick look at [an example](https://github.com/pavouk/lgi/blob/master/samples/gtkhello.lua) for LGI shows the usage for creating a window:
```lua
local window = Gtk.Window {
   title = 'window',
   default_width = 400,
   default_height = 300,
   on_destroy = Gtk.main_quit
}
```
This translates to this in MoonScript:
```moon
window = gtk.Window
  title: 'window'
  default_width: 400
  default_height: 300
  on_destroy: gtk.main_quit
```

Later down in the example, a function is assigned for an event callback:
```lua
function about_button:on_clicked()
   local dlg = Gtk.AboutDialog {
      program_name = 'LGI Demo',
      title = 'About...',
      name = 'LGI Hello',
      copyright = '(C) Copyright 2010, 2011 Pavel Holejšovský',
      authors = { 'Adrian Perez de Castro', 'Pavel Holejšovský', },
   }
   if tonumber(Gtk._version) >= 3 then
      dlg.license_type = Gtk.License.MIT_X11
   end
   dlg:run()
   dlg:hide()
end
```
The colon just translates to a function with "self" as its first argument, which is defined using moonscript's `=>`. This would translate to:
```moon
about_button.on_clicked = =>
   dlg = gtk.AboutDialog 
      program_name: 'LGI Demo'
      title: 'About...'
      name: 'LGI Hello'
      copyright: '(C) Copyright 2010, 2011 Pavel Holejšovský'
      authors: { 'Adrian Perez de Castro', 'Pavel Holejšovský' }

  
   if tonumber(gtk._version) >= 3
      dlg.license_type = gtk.License.MIT_X11

   dlg\run!
   dlg\hide!
```

A last note: using Lua APIs with MoonScript is just taking whatever is documented and translating it directly into its MoonScript equivalent. You _can_ deviate sometimes and do some funky stuff, but I wouldn't recommend it, as it seems your attempt to use classes didn't go so well. Just stick to the docs, and everything will be alright. :+1:

**Comment by handicraftsman** [comment]
Tried
```moonscript
window = gtk.Window
  title: 'window'
  default_width: 400
  default_height: 300
  on_destroy: gtk.main_quit
```
and see:
```
moon: /usr/local/share/lua/5.1/moonscript/base.lua:81: ./win.moon: Failed to parse:
 [6] >>    default_width: 400
```

**Comment by Kingdaro** [comment]
Are you sure? It parses fine for me. Post your full code again? It's possible the issue is somewhere else entirely, and the interpreter is misreporting the error (which is what happened with your first issue, it seems).

**Comment by handicraftsman** [comment]
main.moon:
```moonscript
lgi = require("lgi")
glib = lgi.GLib
gobj = lgi.GObject
gtk = lgi.Gtk

win = require("win")

win.window()
```
win.moon:
```moonscript
window = ->
  gtk.init()

  win = gtk.Window
    title: "Test Moon App"
		default_width: 400
	  default_height: 300
		on_destroy: gtk.main_quit
    --  class box extends gtk.Box
      -- orientation = gtk.Orientation.HORIZOLTAL

  gtk.main()
```

**Comment by Kingdaro** [comment]
The table's tabbing is inconsistent in win.moon. MoonScript is whitespace sensitive, and all lines the table keys are on should have the same number of preceding spaces, save for any nested tables or values.
```moon
window = ->
  gtk.init()

  win = gtk.Window
    title: "Test Moon App"
    default_width: 400
    default_height: 300
    on_destroy: gtk.main_quit

  gtk.main()
```

Also, the code won't operate _quite_ the way you might expect. win.moon doesn't return anything, it just defines a function called "window" in the local scope. Throw this at the bottom of win.moon to return a table with the window function defined, and it should work.
```moon
{ :window }
```

Saying `{ :key }` is the same as `{ key: key }` or `{ key = key }` in Lua. When an expression is the last one in a function or in the entire file, a return is added. So, in the end, this'll compile to `return { window = window }` in Lua. When you run main.moon, it'll receive the window function correctly.

**Comment by handicraftsman** [comment]
At last: how i can run methods inside classes, which are inheirted?

I tried `win\show_all!`, but it not works for me. Again "failed to parse" error.

**Comment by Kingdaro** [comment]
Again, first, check your line spacing and make sure it's consistent. Secondly, **do not use the class syntax here**, as it doesn't seem like MoonScript classes will work well with the LGI classes. Just use the API as it's demonstrated in the docs.

You _can_ use classes which instance the gtk objects, and make simple wrapper functions to them, but that's pretty much it.

**Comment by handicraftsman** [comment]
Sorry - just atom's problem xD

**Comment by ChickenNuggers** [comment]
@handicraftsman I believe either work; I use tabs and set vim to have the tabs equate to four spaces.

**Comment by Kingdaro** [comment]
Mhm. Tabs work as well. They're defined internally by MoonScript as four spaces.
