### ISSUE TITLE
Linter should return 1 if it fails.

### ISSUE THREAD

**Issue by jodonnell** [leafo/moonscript#244]
I want to write a little build script for my app, if the linting fails I would like the build to fail.  It seems like echo $? always returns 0, it would be great if it returned 1 if it found linting issues.

**Comment by ChickenNuggers** [comment]
Wasn't this fixed via https://github.com/leafo/moonscript/commit/0262243136fdbb365c4b685202dba42b5452c828 ?

**Comment by jodonnell** [comment]
that looks like it would fix it, the commit was made after 0.4.0 came out.
