### ISSUE TITLE
Compiler API usage in Android

### ISSUE THREAD

**Issue by darmie** [leafo/moonscript#250]
Hi @leafo , I am trying to use the compiler API within Android. I am working on a framework that uses Moonscript to develop android apps. So I want to be able to use Moonscript directly within android by using the compiler API. I understand there are depedencies, I need your advice on how I may be able to use these dependencies like `LPEG` and the others, within android.

Thanks in advance.

**Comment by leafo** [comment]
Hello,

Are you able to bundle Lua C modules with your application? If so then it's just a matter of building them alongside your Lua runtime into your executable. 

This is how I build standalone windows binaries: https://github.com/leafo/moonscript/tree/binaries

**Comment by leafo** [comment]
BTW, lpeg is the only native dependency. luafilesystem is only required for the command line tools, so wouldn't be needed in your case.

**Comment by darmie** [comment]
Thanks for your quick response @leafo. 

Actually, my framework would be using Luaj and Wax for Android and iOS respectively. This could mean I may have to port lpeg to either Java or Obj-C. 

My primary goal is to be able to update .moon scripts without having to relaunch the app.

**Comment by stevedonovan** [comment]
On Fri, Mar 11, 2016 at 9:21 AM, darmie <notifications@github.com> wrote:

> Actually, my framework would be using Luaj and Wax for Android and iOS
> respectively. This could mean I may have to port lpeg to either Java or
> Obj-C.
>

I've used LuaJava happily - main thing it's the native library with a JNI
bridge, so it can consume lpeg directly.

**Comment by darmie** [comment]
@stevedonovan how do I link Luaj with lpeg via JNI? 

A detailed example would be really appreciated.

**Comment by stevedonovan** [comment]
On Fri, Mar 11, 2016 at 12:22 PM, darmie <notifications@github.com> wrote:

> @stevedonovan <https://github.com/stevedonovan> how do I link Luaj with
> lpeg via JNI?
>
> A detailed example would be really appreciated.
>
>
luaj is a direct-to-JVM bytecode compiler (impressive performance, BTW) so
I suspect you would have to do a translation.

At least it's easier on the iOS side since Objective-C is happy compiling
'normal' C.

**Comment by darmie** [comment]
Ok, thanks I'll try a direct port. I hope it works out fine.

**Comment by stevedonovan** [comment]
On Fri, Mar 11, 2016 at 12:38 PM, darmie <notifications@github.com> wrote:

> Ok, thanks I'll try a direct port. I hope it works out fine.
>
>
Try this out: https://github.com/pygy/LuLPeg   - it's a pure Lua
implementation of lpeg. Could work well enough - if not, I'm sure the guy
will be happy to help.

**Comment by darmie** [comment]
Alright cool. I was going to try that also.

**Comment by darmie** [comment]
@leafo @stevedonovan  Thanks Guys, I finally found a solution to my problem, there's a Java version of `lpeg - 0.10` called  [lpeg/j](https://github.com/leonrd/lpegj) , It has support for `Luaj` so I added it to my android project and loaded it like this 

```lua
package.preload['lpeg'] = function (...)
    return require "org.moon.mooonlanding.lpeg"   -- this looks for the lpeg Java class in the project directory
end
```

This is the rest of my Lua code that parse and executes  the `*.moon` files
```lua
activity = ...

local getScript = function(script)
  return activity:findResource(script)
end

local moonscript = require("moonscript.base")
local parse = require("moonscript.parse")
local MoonApp = activity:readFile("init.moon") --initialize my moon app
local prs = parse.string(MoonApp)
prs()  -- parse the moon file
local run = moonscript.loadstring(MoonApp)
return run()
```

And this is my android activity 

```java
public class MoonActivity extends Activity implements ResourceFinder {
	public Globals lua;
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		
		LuaValue activity = CoerceJavaToLua.coerce(this);
		LuaValue contxt = CoerceJavaToLua.coerce(this.getApplicationContext());
		lua = JsePlatform.standardGlobals();
		lua.finder = this;
		try{
			lua.set("AndroidContext", contxt);
			lua.load(new DebugLib());  //Load Luaj's version of Lua debub library, Moonscript and lpeg need this to work
			lua.loadfile("Moon.lua").call(activity);
		}catch(Exception e){
			e.printStackTrace();
			
		}
	}
	
	public void log (String msg){
		
			try {
				Log.d("MOONSCRIPT", msg);		
			} catch (Exception e) {
				e.printStackTrace();
				
			}
		
	}
	
	public String readFile(String path) {
		String text = "";
		//InputStream myfile = this.findResource(path);
		
			try {
				InputStream is = getAssets().open(path);
		        int size = is.available();
		        byte[] buffer = new byte[size];
		        is.read(buffer);
		        is.close();
		        text = new String(buffer);
		        
		        return text;
		    } catch (Exception e) {
		        // TODO Auto-generated catch block
		        e.printStackTrace();
		    }
			return text;
	}
	
	public void createView(View view) {
		
		Log.d("MOONTEST", view.toString());
		
			try {
				Log.d("MOONTEST", "Show View");
				this.setContentView(view);
		    } catch (Exception e) {
		        // TODO Auto-generated catch block
		        e.printStackTrace();
		    }
		
	}
	
	public Context getCont() {
		
			try {
				
				return this.getApplicationContext();
		    } catch (Exception e) {
		        // TODO Auto-generated catch block
		        e.printStackTrace();
		    }
		
		return this.getApplicationContext();
		
	}
	
	
	@Override
	public InputStream findResource(String name) {
		try {
			return this.getApplicationContext().getAssets().open(name);
		} catch (java.io.IOException ioe) {
			ioe.printStackTrace();
			return null;
		}
	}
}

```

**Comment by ChickenNuggers** [comment]
Would you mind putting this up as either a Git repository or Gist? Besides that, :+1:

**Comment by darmie** [comment]
@ChickenNuggers sure I'll put it up as a github repo and share it on this thread. 😊

**Comment by darmie** [comment]
@ChickenNuggers here's the link to the repository [MoonDroid](https://github.com/darmie/MoonDroid)

**Comment by ChickenNuggers** [comment]
Saw and starred already ^_^; mind closing this issue?
