### ISSUE TITLE
"unless" conditional with assignment fails to compile

### ISSUE THREAD

**Issue by line0** [leafo/moonscript#251]
Moonscript v0.4.0 fails to compile an assignment conditionals with the `unless` keyword (`if` works).

Minimal Sample:
````Moonscript
unless x = true
    -- never encountered
````

Compiler errors out with:
````
Compile error: Failed to find value compiler for: {"assign", {{[7] "ref", "x"}}, {{[11] "ref", "true"}}}
````
Linter dies, too:
````
PANIC: unprotected error in call to Lua API ((null))
````

The reference manual doesn't explicitly state that `unless` in particular can be used with assignment, but as opposed to `if not` there's no apparent reason why it shouldn't work. 
Even if it's not supposed to work, i suppose the compiler should die with a more helpful error message.

**Comment by ChickenNuggers** [comment]
`if not x = true` doesn't work either with native Lua. This is more of a "Unknown error with compiler on bad syntax"

**Comment by line0** [comment]
> if not x = true doesn't work either with native Lua. This is more of a "Unknown error with compiler on bad syntax" than an issue about the syntax?

but that's not what it's supposed to compile to.
````Moonscript
if x = true
    dongs!
````
compiles to 

````Lua
do
  local x = true
  if x then
    return dongs()
  end
end

````

I'll leave it to you to figure out how it'd work with `unless`

**Comment by leafo** [comment]
What scenario would you like to use this syntax?

When you use `if` the variable is only available in the scope of the if block:

```moon
if x = something!
   -- x is only available in this scope
```

When using `unless` the value would be falsy, so I can't imagine why you'd need a reference to it.

**Comment by ChickenNuggers** [comment]
Just to add an example, now that I think of it.
```moonscript
local lfs
unless lfs = tryrequire "lfs"
    lfs = require "syscall.lfs"
```
Imagine that for this scenario tryrequire is a require() that doesn't error but instead just returns false.

**Comment by leafo** [comment]
In that scenario I think it makes more sense to write:

```
lfs = tryrequire "lfs"
unless lfs
    lfs = require "syscall.lfs"
``

**Comment by ChickenNuggers** [comment]
Well, that was a basic example. I'm certain there are better reasons for implementing this.
