### ISSUE TITLE
getopt error on ubuntu

### ISSUE THREAD

**Issue by italomaia** [leafo/moonscript#253]
Hello folks, just installed lua5.3 and liblua on linux. Installed luarocks and moon. When executing moon, I get a "attempt to call a nil value" for getopt. Suggestions on how to work around it?

`
/usr/bin/lua5.3: /home/me/.luarocks/share/lua/5.3/alt_getopt.lua:24: attempt to call a nil value (global 'module')
stack traceback:
	/home/me/.luarocks/share/lua/5.3/alt_getopt.lua:24: in main chunk
	[C]: in function 'require'
	....luarocks/lib/luarocks/rocks/moonscript/0.4.0-1/bin/moon:2: in main chunk
	[C]: in ?
`

**Comment by ChickenNuggers** [comment]
Please see #242 - you'll need to compile a custom Lua with `-DLUA_COMPAT_MODULE` iirc.

**Comment by italomaia** [comment]
How do I do that?

**Comment by ChickenNuggers** [comment]
**You must first remove your system-installed Lua version**
```sh
curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar -xz
cd lua-5.3.2/
make linux
sudo make install
```
Try that?

**Comment by italomaia** [comment]
Should liblua be removed too? There is a lot of dependencies to it here (ubuntu)

**Comment by ChickenNuggers** [comment]
If there are dependencies, it is probably not a smart idea to remove the
Lua install. Your best bet might be to just use Lua 5.1 (iirc LuaRocks
for Ubuntu defaults to using 5.1).

**Comment by leafo** [comment]
More reasons to get rid of this library! Sorry for the trouble.

**Comment by fendrin** [comment]
```bash
sudo apt-get remove luarocks
sudo apt-get install lua5.3
sudo apt-get install liblua5.3-dev
sudo ln -s /usr/lib/lua5.3 /usr/lib/lua
```
Then follow the unix installation instructions at luarocks.org because the ubuntu version does not fetch 5.3 libs.
Install moonscript with the new luarocks.

Works for me on Ubuntu 15.10

**Comment by italomaia** [comment]
@fendrin so, moonscript installed with compiled luarocks did not work for me BUT, when installed with luarocks from ubuntu repository, it worked like a charm. Thanks, folks!
