### ISSUE TITLE
Code coverage error

### ISSUE THREAD

**Issue by pavel** [leafo/moonscript#264]
Running simple test from http://moonscript.org/reference/command_line.html#command-line-tools/moon/code-coverage:

1. Created a file `test.moon`
```moonscript
-- test.moon
first = ->
  print "hello"

second = ->
  print "world"

first!
```

2. Running `moon -c test.moon`

3. Error:
```
starting coverage
hello
/usr/bin/lua: .../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:45: @test.moon: No such file or directory
stack traceback:
	[C]: in function 'assert'
	.../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:45: in upvalue 'format_file'
	.../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:119: in function <.../myuser/.luarocks/share/lua/5.3/moonscript/cmd/coverage.lua:86>
	(...tail calls...)
	[C]: in ?
```

When I create file `@test.moon`, I get this output:
```
starting coverage
hello
------| @@test.moon
     1| 
```
File `@test.moon` is empty.

**EDIT**: From what I understand seems like the coverage tool tries to open "@test.moon" file, which is not there. Probably removing this first "@" will fix the issue.

---
`lua -v`: `Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio`
`moon -v`: `MoonScript version 0.4.0`

**Comment by ChickenNuggers** [comment]
I'll look more into this when I get home, look at #265, and probably add some kind of test to make sure that this works in the future.

**Comment by ChickenNuggers** [comment]
@pavel The actual cause behind this is that when the files have `debug.getinfo()` run on them, MoonScript uses a "cheat" to find out what file is used - Lua prepends this file with "@". What you should do with your branch is, when `debug.getinfo(2, "S")` is run, get the `:sub(2)` of the `.source` field instead. Do you mind patching that up?

**Comment by pavel** [comment]
@ChickenNuggers What is the difference in using `:sub(2)` on the `.source` instead of the current solution?

**Comment by ChickenNuggers** [comment]
You're passing the proper filename exactly from when you get it. It makes it seem like less of a hack and more of a solution and also notes that `.source` is the reason why you need to `:sub(2)`

**Comment by pavel** [comment]
This change
```diff
diff --git a/moonscript/cmd/coverage.lua b/moonscript/cmd/coverage.lua
index 9bc2c79..21474b6 100644
--- a/moonscript/cmd/coverage.lua
+++ b/moonscript/cmd/coverage.lua
@@ -42,7 +42,7 @@ position_to_lines = function(file_content, positions)
 end
 local format_file
 format_file = function(fname, positions)
-  local file = assert(io.open(fname:sub(2)))
+  local file = assert(io.open(fname))
   local content = file:read("*a")
   file:close()
   local lines = position_to_lines(content, positions)
@@ -80,7 +80,7 @@ do
     end,
     process_line = function(self, _, line_no)
       local debug_data = debug.getinfo(2, "S")
-      local source = debug_data.source
+      local source = debug_data.source:sub(2)
       self.line_counts[source][line_no] = self.line_counts[source][line_no] + 1
     end,
     format_results = function(self)
```
does not work for me.
When I run `moon -c test.moon` I get the following output:
```
starting coverage
hello
```
and nothing more.

@ChickenNuggers Any thoughts?

**Comment by ChickenNuggers** [comment]
I guess revert it if it gives an error; I'm not really able to look at the spaghetti ATM.
