### ISSUE TITLE
Constructor argument returns a table

### ISSUE THREAD

**Issue by darmie** [leafo/moonscript#266]
I tried passing argument to class constructor `new` , argument passed was a string, but it's been seen as a table

```moon
class myClass
      new: (data)->
        print data

value = "Boy"

myClass(value)
```

result

```log
table: 0x1330b30
```

**Comment by darmie** [comment]
Fixed by using `=>` instead of `->` why do they behave differently?

```moon
class myClass
      new: (data) ->
        print data

value = "Boy"

myClass(value)  -- table: 0x1330b30
```


But this worked

```moon
class myClass
      new: (data)=>
        print data

value = "Boy"

myClass(value) -- Boy
```

**Comment by Kingdaro** [comment]
The fat arrow creates a function that takes `self` as a first parameter. The skinny does not. In other words, these are equivalent:
```moon
myfunc = (self, rest) ->
myfunc = (rest) =>
```

**Comment by darmie** [comment]
Yes, noted. I was just wondering why I must use a fat arrow for a constructor. But it's now clear to me
