### ISSUE TITLE
[Syntax Idea] Pipe operator becomes "for" loop

### ISSUE THREAD

**Issue by ChickenNuggers** [leafo/moonscript#270]
**Concept:**

Use `|>` as a `for` loop generator.

**Example:**

```moonscript
yourGenerator! |> yourThing
```

Compiles to:

```lua
while true do
  local _vararg_0 = {yourGenerator()}
  if not _vararg_0[1] then
    break
  end
  yourThing(unpack(_vararg_0))
end
```

**Conflicts:**

Using yourThing with extra parameters:

```moonscript
yourGenerator! |> yourThing(x, y, a, b, <|)
```

Compiles to:

```lua
while true do
  local _vararg_0 = {yourGenerator()}
  if not _vararg_0[1] then
    break
  end
  yourThing(x, y, a, b, unpack(_vararg_0))
end
```

**Comment by Idyllei** [comment]
I feel that this syntax is too niche, and the niche has already been filled -- by the ```for``` loop! 

If the ```|>``` syntax solves a problem or makes a specific pattern easier to use (like comprehensions have), then I would likely support it. But seeing as this syntax is, at first glance, unintuitive, this proposal doesn't have my support.

(Consider refining the idea further, or give Moonscript examples, not Lua; it would be easier to decide whether or not the feature should or should not be adopted.)

**Comment by ChickenNuggers** [comment]
I understand that for loops already exist; I just thought this could be a quicker to type and more convenient way to do something like this.

**Comment by leafo** [comment]
Interesting idea, but can be accomplished for a for loop and a function. I only want to create new operators if there's a clear advantage for them.

you could write a function  lets you do `pipe(generator, consume, arg1, arg2)` pretty easily, so I don't think syntax is necessary.
