### ISSUE TITLE
Installation error with luarocks

### ISSUE THREAD

**Issue by ram-nadella** [leafo/moonscript#272]
I get the following error when I try to install moonscript using luarocks
```sh
$ sudo luarocks install moonscript
Warning: Failed searching manifest: Failed extracting manifest file
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/moonscript-0.4.0-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/moonscript-0.4.0-1.src.rock... switching to 'build' mode

Error: Failed unpacking rock file: /tmp/luarocks_luarocks-rock-moonscript-0.4.0-1-7897/moonscript-0.4.0-1.src.rock
```

Tried another random rock ([mpack](https://luarocks.org/modules/tarruda/mpack)) to check if it's my setup, but that worked fine.

Don't know how to debug this further, any tips?

**Comment by Guard13007** [comment]
Try it again with `--verbose` to see more info about what is failing.

**Comment by ChickenNuggers** [comment]
Make sure that you have the `zip` and `unzip` commands installed. For Arch Linux this would be `pacman -S zip unzip`.

**Comment by ram-nadella** [comment]
@ChickenNuggers you are right, it tuned out to be because of missing `unzip`

@Guard13007 thanks for the `--verbose` tip

```sh
$ sudo luarocks install moonscript --verbose

...

os.execute: 	cd '/home/vagrant/.cache/luarocks/https___luarocks.org' && unzip -n '/home/vagrant/.cache/luarocks/https___luarocks.org/manifest-5.1.zip'
sh: 1: unzip: not found
Results: 1
  1 (number): 32512

...

Error: Failed unpacking rock file: /tmp/luarocks_luarocks-rock-moonscript-0.4.0-1-4304/moonscript-0.4.0-1.src.rock
```

For anyone else that runs into the same issue, I fixed it by installing unzip (I am on Ubuntu, should work for Debian too)

```sh
sudo apt-get install unzip
```

Interestingly enough, the [installation docs](https://github.com/keplerproject/luarocks/wiki/Download#requirements) for luarocks say unzip should just be available on most linux distros (not the case for Ubuntu 14.04 😃) and they decide [how to uncompress](https://github.com/keplerproject/luarocks/blob/0d11ac64fc6b513cf7940699ff57303366bccbe2/src/luarocks/fs/unix/tools.lua#L303-L311) based on the file extension.

I believe a `.zip` file can be uncompressed by `gunizp`, right?

**Comment by Guard13007** [comment]
Well, `unzip` is on *most* Linux distros, but Ubuntu is a bit of special.

As for using `gunzip` instead, don't do it. There's a way (I think) to do that, but it's not recommended, and `gunzip` can only unzip a zip file with a *single file* compressed with the deflation method. (I'm guessing) It will probably break far worse if you try to set it up that way.

**Comment by ChildishGiant** [comment]
I'm on windows and having the same issue. Verbose doesn't seem to add any extra logging
```
PS C:\Windows\system32> luarocks install moonscript --verbose
Installing http://luarocks.org/repositories/rocks/moonscript-0.5.0-1.src.rock...

Error: Failed unpacking rock file: C:\Users\allie\AppData\Local\Temp\luarocks_luarocks-rock-moonscript-0.5.0-1-1592/moonscript-0.5.0-1.src.rock
```

**Comment by brostosjoined** [comment]
@ChildishGiant  Did you manage to get a solution for it??
