### ISSUE TITLE
Discrepancy between bracket-full and bracketless syntaxes

### ISSUE THREAD

**Issue by Awpteamoose** [leafo/moonscript#274]
This compiles:
```moonscript
fn foo,
    bar,
    baz
```

This doesn't:
```moonscript
fn(foo,
    bar,
    baz
)
```

It's odd, especially since brackets are supposed to reduce ambiguity.

**Comment by ChickenNuggers** [comment]
This issue has already been reported; too lazy to find it ATM though.
