### ISSUE TITLE
[Stdlib] add custom starting accumulator to fold

### ISSUE THREAD

**Issue by LudwikJaniuk** [leafo/moonscript#275]
Yes, the current version of fold can sum a list of numbers (*but not an empty one!*). But as soon as we want to do something more complicated where the accumulator is not of the same type as the elements, or we need to tolerate an empty list with some identity value, the current `fold` is unusable.

I propose the you add another argument or another version of the function that would allow people to provide their own starting accumulator. See `fold` vs `fold1` in Haskell.

**Comment by leafo** [comment]
I plan to deprecate the moon module, and only include things that are specific to the MoonScript generated code (like working with class objects).

Utility methods like these are better suited to a separate module.
