### ISSUE TITLE
Nested if else

### ISSUE THREAD

**Issue by Romaboy** [leafo/moonscript#276]
I learned how to use source code markup! It's pretty useable. Previously I had tried to paste code with `inline` syntax.
So this nested conditions
```moonscript
if 1
  if 2
    3
  elseif 4
    5
else 6
```
Become to this:
```lua
if 1 then
  if 2 then
    return 3
  elseif 4 then
    return 5
  else
    return 6
  end
end
```

It is confusing, fix please

**Comment by Guard13007** [comment]
The `6` should be on the next line.

```
if 1
    if 2
        3
    elseif 4
        5
else
    6
```

Turns into

```
if 1 then
  if 2 then
    return 3
  elseif 4 then
    return 5
  end
else
  return 6
end
```

**Comment by Romaboy** [comment]
Thanks, Guard, it works!

**Comment by Guard13007** [comment]
I still think something should be done about this, because that syntax should error or be interpreted correctly.

**Comment by Romaboy** [comment]
I can reopen issue and leafo maybe fix it. But with new line it works, and leafo has many projects and more important things, so, should I reopen it? Ok, let it be open.

**Comment by Guard13007** [comment]
At the very least I think we should get his opinion on it. @leafo Thoughts?

**Comment by leafo** [comment]
parsing error, fixed for next release. Thanks
