### ISSUE TITLE
loadstring for moonscript

### ISSUE THREAD

**Issue by Positive07** [leafo/moonscript#279]
What I'm actually asking is for a Lua function I can call to evaluate moonscript code, it would work the same way `loadstring` does for Lua code, but it would parse moonscript code instead and would return a function code than when called would evaluate the generated moonscript code.

Is this possible? I'm guessing it is since it would pretty much as `require "moonscript"` does right now

```lua
f = loadmoon[[
   -- Moonscript code
   collection =
      height: 32411
      hats: {"tophat", "bball", "bowler"}
   collection --Return value?
]]

collection = f()

print(collection.height) --32411

for i=1, #collection.hats do
   print(collection.hats[i])
end
```

**Comment by leafo** [comment]
yup, see here: http://moonscript.org/reference/api.html#moonscript-compiler-api/moonscriptbase-module

**Comment by Positive07** [comment]
I'm sorry I couldn't find it when I searched but seems I didn't look through very well, I'm closing this, thanks!
