### ISSUE TITLE
win32-v0.4.0 is missing lua5.1.dll

### ISSUE THREAD

**Issue by brashaw** [leafo/moonscript#281]
[The latest release](https://github.com/leafo/moonscript/releases/tag/v0.4.0) is missing lua5.1.dll.  Trying to run `moon.exe` or `moonc.exe` errors with:

>The program can't start because lua5.1.dll is missing from your computer.  Try reinstalling the program to fix this problem.

I fixed the issue for myself by copying the lua5.1.dll from [a previous release](https://github.com/leafo/moonscript/releases/tag/v0.2.4) into the MoonScript directory.

**Comment by sliceofcode** [comment]
You can also copy `lua51.dll` to `lua5.1.dll` in the same directory.

**Comment by leafo** [comment]
Thanks, updated the build code. Will contain the file for next release.

**Comment by leafo** [comment]
or you can download master here: https://ci.appveyor.com/project/leafo/moonscript/build/artifacts
