### ISSUE TITLE
Possibility to specify source directory?

### ISSUE THREAD

**Issue by LudwikJaniuk** [leafo/moonscript#293]
When running `moonc --help`, there is an option to specify where output will be placed, but I don't see an option to specify a source directory - a directory where moonc would look for input files. 

I might be missing something, but if not, I think this would be a really useful feature to have. It would allow for a more organized project structure.

**Comment by LudwikJaniuk** [comment]
My mistake, this is totally already working, just spedify a directory instead of the files. If anything, I could just ask for it to be more clearly speficied in the docs printed. Will make PR for it.

**Comment by LudwikJaniuk** [comment]
@leafo Any update on this? The PR is quite small...

**Comment by leafo** [comment]
woop, sorry. merged now, thanks
