### ISSUE TITLE
Command line output changed in 0.5, now it refreshes constantly

### ISSUE THREAD

**Issue by travisbell** [leafo/moonscript#295]
Hi @leafo,

This is maybe something small, but it's kind of annoying working on my MoonScript project now... so I updated to 0.5 and have always in the past used this command to monitor my local .moon files and write them as I work:

`cache/luarocks/bin/moonc -w .`

Worked like a charm, the only updates to stdout were when I changed a file. Otherwise it was completely silent. However, In 0.5 now, the output of moonc prints the whole file list to stdout every few seconds (maybe even every second?) This might not seem like a big deal but now I miss if there's a syntax error or an issue when trying to compile the .lua file. The error prints but is gone off screen within a second as the file list refreshes and prints the same thing over and over again.

Is there a command to stop the refreshes from printing to stdout? Nothing seemed obvious to me.

Thanks!

**Comment by leafo** [comment]
sorry about that, a print statement got left behind during a refactor. Fix is pushed to master, will have a release out sometime in the near future

**Comment by travisbell** [comment]
Ok, great! Thanks, I appreciate all the work you do man ;)
