### ISSUE TITLE
`~=` as update assignment

### ISSUE THREAD

**Issue by Nymphium** [leafo/moonscript#296]
The language has `!=` as not-equal comparison operator, on the other hand it has `~=`, the same operator.
Then, I suggest the former `~=`  to be `x = ~ y`, applying the bitwise not operation and assigning the variable.

**Comment by kirbyfan64** [comment]
That would be kind of confusing, since Lua uses `~=` for not-equal.

**Comment by Guard13007** [comment]
@Nymphium The language also has `~=` as a not-equal comparison operator already. :/

**Comment by Nymphium** [comment]
Yes I know, but I think just one operator is enough for us.

**Comment by ChickenNuggers** [comment]
I feel like people who come over from Lua are going to have serious issues adjusting. Besides, this far into development, it's not a good idea to completely "reassign" an operator.

**Comment by Nymphium** [comment]
Okay, I'll reconsider.
