### ISSUE TITLE
Livescript port

### ISSUE THREAD

**Issue by ceremcem** [leafo/moonscript#302]
Hi, 

As we heavily use Livescript rather than Coffeescript, we would love to create a port or an option for Livescript. 

Would you lead us if there are some shortcuts came in your mind? For example I guess AST would be a common base. What do you think?

**Comment by leafo** [comment]
Are you saying you'd like to assemble something that compiles Livescript to Lua? The MoonScript syntax has diverged from CoffeeScript, CoffeeScript is just an inspiration. There is an intermediate AST but it's not documented, you'd have to look through the code. If you compile with the `moonc -T somefile.moon` then you can get the AST dumped out. The AST is s-expressions inside of Lua tables.

**Comment by ceremcem** [comment]
That's exactly what I wanted to do. But as you say MoonScript is diverged from CoffeeScript, I may put this idea aside for now and start using MoonScript as is. Thank you.
