### ISSUE TITLE
Function Parameters nil

### ISSUE THREAD

**Issue by AndrewBastin** [leafo/moonscript#303]
Hi there,

I am not sure if this is the right place to put this.. Anyways, I just started using Moonscript out of curiosity.. I really liked the syntax (haven't used coffee before though).. So, I thought of working on a LOVE game on it and I ran into this issue..

NOTE : I am coming from C# and have not ventured much scripting and lua and stuff.. So, please forgive me if I mixed in some concepts and keywords here and there :P

I have this Entity class, having a table (in an array fashion) with 1 component (type of Component class) as a property..
It has a function called addComponent which takes a component as a parameter and adds it to the component table. But the thing is, the parameters, self and component are being called as nil.

Entity class:
~~~~
import Component from require 'ecs.component'
import Transform from require 'components.transform'

class Entity
  name: "" -- Name of the Entity
  transform: Transform 0, 0, 0, 0, 0
  components: { transform } -- Component table of the entity

  new: (@name, @transform) =>
    @components = { transform }

  -- Adds a component to the components table
  -- component : Expected to be of ecs.component type
  addComponent: (component) =>
    -- Component is null
    for i = 1, table.getn @components -- Self is null
      if table[i].__name == component.__name
        -- This component already exists in the entity... We will replace it
        table.remove(@components, i)
        table.insert(@components, component)
        return -- Not safe to modify this array anymore...

    table.insert(@components, component) -- We havent found any existing component like that, so just add it

{ :Entity}
~~~~

I loaded it in main.moon in love.load:
~~~~
love.load = () ->
  love.window.setTitle "Testing Moonscript"
  testEntity = Entity "Test Entity", Transform 10, 10, 10, 10
  testEntity.addComponent SpriteRenderer!
~~~~

And then pops up the error : 
~~~~
bad argument to #1 to 'getn' (table expected, got nil)
~~~~
I am happy to provide more code if requested...

Thank You...

**Comment by just-nobody** [comment]
You'll want to use the self `\` function call instead of the dot `.`.
```moon
love.load = () ->
  love.window.setTitle "Testing Moonscript"
  testEntity = Entity "Test Entity", Transform 10, 10, 10, 10
  testEntity.addComponent SpriteRenderer!
```

Reasoning: functions defined with a fat arrow `=>` is the same as defining it with `self` as the first parameter. So `func = =>` is the same as `func = (self) ->`. When you called `addComponent`, it didn't receive the argument properly.

**Comment by AndrewBastin** [comment]
@just-nobody Oh okay... I get it now. Thank you!!!

**Comment by AndrewBastin** [comment]
Well, sorry for that... But still I am getting nil for both the params..

**Comment by AndrewBastin** [comment]
Well sorry about that.. thought the params were still nil.. Turns out I wrote the assert to check the wrong way... Man... I need to get some sleep...
