### ISSUE TITLE
moonc -w background support

### ISSUE THREAD

**Issue by transifex3** [leafo/moonscript#305]
For now i need to open another terminal or use Ctrl+Z, but I think it would be good to add native support for background work in moonc

**Comment by leafo** [comment]
can you run `moonc -w &`?

**Comment by transifex3** [comment]
![1111](https://cloud.githubusercontent.com/assets/16120391/20956938/52109ce4-bc90-11e6-9a81-6fabd2a160c0.png)

I've tried but it outputs like this. Enter key to escape from outputs, does not work.

**Comment by ChickenNuggers** [comment]
Background support means pulling in a C library. Try `moonc -w >/dev/null 2>/dev/null &`.

**Comment by transifex3** [comment]
@ChickenNuggers 

I've checked your reply late, Sorry 😢 

![11aa](https://cloud.githubusercontent.com/assets/16120391/21268556/a5e7a290-c3f2-11e6-9526-1f5e8c9442e7.png)

This one seems working well. thanks!

**Comment by ChickenNuggers** [comment]
@transifex3 mind closing the issue, if this works?
