### ISSUE TITLE
broken multi-line `if`

### ISSUE THREAD

**Issue by buckle2000** [leafo/moonscript#308]
Consider the following code:
```
      if (vyi > y) ~= (vyj > y) and
          x < (vertices[j*2-1]-vxi) * (y-vyi) / (vyj-vyi) + vxi
        inside = not inside
```
This statement is valid in [the online compiler](http://moonscript.org/compiler/)
but invalid when using `moonc`.

**Comment by leafo** [comment]
Does the version you're using on the command line match the one on the online compiler?

**Comment by buckle2000** [comment]
My fault. I was using `moonc` of v0.2.5.
