### ISSUE TITLE
Support goto Statement

### ISSUE THREAD

**Issue by buckle2000** [leafo/moonscript#321]
http://lua-users.org/wiki/GotoStatement
`goto` and `::label::` are introduced in lua 5.2. I think moonscript should support goto statement.

**Comment by Nymphium** [comment]
`goto` statement is incompatible with indent-sensitive.

**Comment by buckle2000** [comment]
Don't understand.

**Comment by Guard13007** [comment]
Goto's and labels fundamentally lead to bad code... :/

**Comment by RyanSquared** [comment]
Duplicate of https://github.com/leafo/moonscript/issues/125

**Comment by buckle2000** [comment]
...
