### ISSUE TITLE
support destructor

### ISSUE THREAD

**Issue by avaicode** [leafo/moonscript#324]
I mean,just like ~class() that's in c++.
Destructor can be called when gc to free resources from filesystem or c.

**Comment by RyanSquared** [comment]
if i recall correctly just make a __gc method in the class

**Comment by buckle2000** [comment]
Impossible. Only `userdata` can have their `__gc` called.
https://www.lua.org/manual/5.1/manual.html#2.10.1

**Comment by RyanSquared** [comment]
Get with the times; the ability to use __gc on tables was added in 5.2. :P

**Comment by kirbyfan64** [comment]
FWIW, LuaJIT doesn't support `__gc`.

**Comment by buckle2000** [comment]
True, `__gc` for tables is avaliable in 5.2.

Anyway, a `__gc` function should be enough for finalizing.

**Comment by RyanSquared** [comment]
As a note:

```
The base object is stored in __base. We can modify this table to add functionality to instances that have already been created and ones that are yet to be created.
```
I think you can just edit `MyClass.__base.__gc` ?
