### ISSUE TITLE
Support all characters as variable name

### ISSUE THREAD

**Issue by buckle2000** [leafo/moonscript#328]
It is legal to do such thing in ~~original lua~~ LuaJIT.
`变量 = 0`
`表.成员 = 0`

**Comment by Nymphium** [comment]
Legal? I got an error:
```
> 变量 = 0
stdin:1: unexpected symbol near '<\229>'
```

**Comment by buckle2000** [comment]
Oh, it is supported in at least LuaJIT.
![default](https://cloud.githubusercontent.com/assets/10850402/23099292/0e81f5f2-f69e-11e6-98ac-5569b99aaf44.PNG)

**Comment by Nymphium** [comment]
Additionaly, LuaJIT 2.1.0-beta2 doesn't support this feature. I think it is not needed, too.

**Comment by RyanSquared** [comment]
For this to transpile into proper Lua it would have to be modified in a way that would be much more difficult to reverse back to the original characters. I think it's better that we don't need to modify the names of variables and/or indexes.
