### ISSUE TITLE
Is it possible to define private instance variables/methods?

### ISSUE THREAD

**Issue by svermeulen** [leafo/moonscript#337]
I have read through the docs but I'm still unclear on whether it is possible to have private methods and private data that is only accessible from within the class.

I see that it is possible to create private static methods and data like this:

```
class Things
  @class_var = "hello world"

  @foo: =>
    print(@class_var)

  run: =>
    @@foo()

t = Things()
t\run()
```

Is there something similar for private data/methods or do those always have to be mixed in with public data/methods?

**Comment by RyanSquared** [comment]
There is no way to make data "private" using the class system MoonScript currently uses. To make data "private", it would need to be obfuscated by the compiler or implemented using a closure for each class instance - which would require a major re-do of MoonScript's class functionality.

**Comment by svermeulen** [comment]
Ok, in that case I'll just use a convention like '_' prefix or something.  Thanks.
