### ISSUE TITLE
Discussion: support : for method invocation (alternative to \)

### ISSUE THREAD

**Issue by hlship** [leafo/moonscript#344]
I'd like to open a discussion about supporting `:` as the method invocation operator (currently `\`).

The use of `\` is perhaps the most puzzling aspect of MoonScript; it's an awkward key to type on most keyboards, it looks awkward in the source (and, hey, I wrote Clojure as my day job!), and it appears to me that the parser could have recognized `:` as easily as `\`, which would align MoonScript with Lua better.

At the very least, I'd love to hear the reasoning or rationale behind this part of the syntax.

And thanks ... MoonScript makes Lua so much more palatable for the things I want to work on.

**Comment by leafo** [comment]
The parser change is not a simple character swap

Here are my thoughts on the matter from a previous ticket:
https://github.com/leafo/moonscript/issues/35#issuecomment-4160278

**Comment by hlship** [comment]
Thanks!  You might want a link to that issue as a footnote in the documentation where you introduce `\`.
