### ISSUE TITLE
Passing function as an argument to another function

### ISSUE THREAD

**Issue by twentytwoo** [leafo/moonscript#348]
I couldn't find any mention of this anywhere on the Reference Manual (or online), I'm trying to do;
```lua
func_a(function() func_b() func_c() end)
```
So far I've tried
```moonscript
func_a(-> func_b() func_c())
```
Which renders as
```lua
local func_a = (function()
  return func_b()(func_c())
end)(function() end)
```
Which doesn't work :/ It works fine for single functions, e.g. `func_a(-> func_b())`

Right now I'm just resorting to
```moonscript
  collectNewReport = () ->
    love.report = love.profiler.report('time', 9)
    love.profiler.reset()

  Timer.every(1, -> collectNewReport())
```
Which is and ugly solution compared to,
```lua
Timer.every(1, function()
    love.report = love.profiler.report('time', 9)
    love.profiler.reset()
end)
```
Any pointers?

**Comment by buckle2000** [comment]
Just don't use brackets
  
  
  

  
  
  
  
  
>

**Comment by buckle2000** [comment]
Timer.every 1, ->
  
       Dothis!
  
       Dothat!
  
  
  

  
  
  
  
  
>

**Comment by RyanSquared** [comment]
Have you tried spacing them out across multiple lines?

```moon
Timer.every 1, ->
  love.report = love.profiler.report('time', 9)
  love.profiler.reset!
```

It works fine with the online compiler.

**Comment by leafo** [comment]
Different statements must be on their own lines. Instead of:

```moonscript
func_b() func_c()
```

you should write
```moonscript
func_b()
func_c()
```

So with your whole example:

```moonscript
func_a ->
  func_b()
  func_c()
```
(note that `!` can be used in place of `()` when calling function with no arguments)

**Comment by twentytwoo** [comment]
Just for clarity, what if I happen to want;
```lua
func_a(function() func_b func_c end, "somethingthatisntafunction")
```

**Comment by leafo** [comment]
this is probably the nicest way to write it: 

```moonscript
func_a(
  ->
    func_b()
    func_c()
  "somethingthatisntafunction"
)
```

You could also do this:

(note that whitespace is an operator in moonscript, so where you put it matters)

```moonscript
func_a (->
    func_b()
    func_c()
), "somethingthatisntafunction"
```

**Comment by twentytwoo** [comment]
Alright, thanks! 👍
