### ISSUE TITLE
IIFE (immediately called function)

### ISSUE THREAD

**Issue by aleclarson** [leafo/moonscript#359]
```moon
foo = do ->
  -- code goes here
  return ->
```

Just like in CoffeeScript, I think an IIFE syntax would be very useful for creating a scope and putting its return value into a variable.

Why can't I use `do` alone? Because I want to do `return ->` inside the scope, but `do` does not work like that. Instead, the outer scope is returned.

```moon
foo = do
  -- code goes here
  -> -- looks weirder than `return ->`
```

Is this too nitpicky?

**Comment by aleclarson** [comment]
Oh, I suppose I can just do:

```moon
call = (fn) -> fn!

foo = call ->
  -- code goes here
  return ->
```

**Comment by vendethiel** [comment]
Coffee’s `do` is slightly more interesting, you can write e.g. `do (f = 1, g, h) ->` to capture values.
