### ISSUE TITLE
destructuring without braces

### ISSUE THREAD

**Issue by aleclarson** [leafo/moonscript#362]
This compiles:
```moon
:foo = tbl
```

This does not:
```moon
if tbl ~= nil
  :foo = tbl
```

Is this by design?

**Comment by RyanSquared** [comment]
Judging by the lack of documentation, I am surprised that `:foo = tbl` even works. I wouldn't rely on it due to it being an undocumented feature.

**Comment by aleclarson** [comment]
Too bad. I like the simplicity of the syntax! Good point, though.

**Comment by leafo** [comment]
Just to answer your question a bit more, the syntax is valid. Not sure why it was never documented. It was brought over from coffeescript. I personally never use it though, so maybe it's a good candidate for removal?

As for the parse error, the following two forms are broken for the same reason:

```moonscript
if hello
  :foo = tbl
```
```moonscript
if hello
  one: "two"
```

There's a indentation precedence issue. It's definitely a bug.

**Comment by johnae** [comment]
I've used the syntax quite extensively. Not sure I care that much about it,
however, quite a bit of code I've written would suddenly become invalid so
I'd still prefer if it wasn't removed. I was always under the impression it
was valid syntax.

Den ons 11 apr. 2018 08:52leaf <notifications@github.com> skrev:
