### ISSUE TITLE
Why suffix `_0` in the compiled code?

### ISSUE THREAD

**Issue by xiangnanscu** [leafo/moonscript#366]
Hello, I've never seen suffix  bigger like `_1` or `_2` , so why not just delete the suffix and make the compiled code more beautiful? for example
```
class Thing
  name: "unknown"
```
compiles to
```
local Thing
do
  local _class_0
  local _base_0 = {
    name = "unknown"
  }
  _base_0.__index = _base_0
  _class_0 = setmetatable({
    __init = function() end,
    __base = _base_0,
    __name = "Thing"
  }, {
    __index = _base_0,
    __call = function(cls, ...)
      local _self_0 = setmetatable({}, _base_0)
      cls.__init(_self_0, ...)
      return _self_0
    end
  })
  _base_0.__class = _class_0
  Thing = _class_0
end
```

**Comment by leafo** [comment]
there's no particular reason, the free variable generator happens to use that naming convention. I have no plans to change it right now. It should be reasonably complex to prevent people from accidentally trying to reference or change it. (Although in the future, a compiler error when a programmer tried to access it would be more appropriate)

**Comment by xiangnanscu** [comment]
thanks
