### ISSUE TITLE
Portable moonscript

### ISSUE THREAD

**Issue by JlnWntr** [leafo/moonscript#370]
Please make moonscript portable, so that you could run your moonscripts like this:

`$ lua moonscript.lua hello.moon
`
(For one example) this has the advantage, that you could use moonscript in **any** (C-/C++-) application that is extended by a Lua-interpreter.

**Comment by leafo** [comment]
moonscript is already coded as a library and a command line tool. You can read the docs here: https://moonscript.org/reference/api.html

moonscript depends on one C library, [lpeg](http://www.inf.puc-rio.br/~roberto/lpeg/), to compile code though. It's relatively easy to compile that code into your project. The `binaries` branch has an example of that: https://github.com/leafo/moonscript/tree/binaries

**Comment by JlnWntr** [comment]
https://moonscript.org/reference/api.html:
> After **installing** MoonScript, you can include the moonscript module to make any Lua script MoonScript aware.

Is it possible to use MoonScript via Lua **without installing** it?
This example here:
```moonscript = require "moonscript.base"
fn = moonscript.loadstring "10"
print fn! -- prints "10"
```

results to that error:

> $ lua test_moon.lua
lua: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

Thanks for your answer.

**Comment by leafo** [comment]
I'm not sure I follow. The error you're getting is because your lua binary appears to be broken (possible compiled on an older system state or different machine).

moonscript is written in lua, it needs a lua runtime. it's possible to compile both lua and moonscript into your program though

**Comment by JlnWntr** [comment]
Okay I've just installed a fresh Ubuntu 18 LTS. This is what I did next:
```
sudo apt-get install libreadline-dev
curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
tar zxf lua-5.3.5.tar.gz
cd lua-5.3.5
make linux test
sudo make install
mkdir git
cd git
git clone https://github.com/leafo/moonscript.git
cd moonscript
lua test_moon.lua 
lua: test_moon.lua:3: syntax error near 'fn'
```
The content of test_moon.lua is:
```
moonscript = require "moonscript.base"

fn = moonscript.loadstring 'print "hi!"'
fn!
```

**Comment by leafo** [comment]
You wrote moonscript code in your `lua` file. moonscript code can't be executed unless run by the moonscript compiler. Try writing it in lua to boostrap the moonscript compiler.

**Comment by JlnWntr** [comment]
Done! 

## test_moon.lua

    local load_file = function(name)
      local file, err = io.open(name)
      if not file then return nil, err end
      local code = assert(file:read("*a"))
      file:close()
      return code
    end

    moonscript = require "moonscript.base"

    -- Load moon script
    local file = load_file("hello.moon")

    -- Compile to lua
    local lua_code = moonscript.to_lua(file)

    -- Run new lua code
    local run = load(lua_code); assert(run); run()

    -- Test
    print("moon_func(2) = " .. tostring(moon_func(2)))

## hello.moon

    print "hi!"
    export moon_func = (x) -> x + 2
