### ISSUE TITLE
function call should take precedence over inflix operators

### ISSUE THREAD

**Issue by sourcevault** [leafo/moonscript#381]
I think function calls should take precedence over inflix operators in `moonscript`.

Currently inflix is processed first:

```moonscript

multi = (a) -> a*2

print (multi 1) + (multi 3) -- 8

print multi 1 + multi 3 -- 14
```

I agree it might break existing `moonscript` codebase. So the change should be made in `moonscript 2.0`

**Comment by RyanSquared** [comment]
I strongly disagree with this; `x y + 1` would be valid both before and after; before as a function call, after as an expression statement. If you really need precedent, use: `multi(1) + multi(3)`.

**Comment by sourcevault** [comment]
Alright, I have no problem with whatever is finally decided, I just found the change in order unexpected. 
```
multi call 1 add multi call 3
```
If you think in terms of BIDMAS rules the `call` operator is even above the brackets, while add and subtract have the lowest precedence.

**Comment by leafo** [comment]
Looks like I only replied on discord. The precedence of function calling in this scenario will not change, and will probably never change! You're welcome to fork though :)

BTW this syntax is inspired by what coffeescript does, and works the same as that.
