### ISSUE TITLE
The @ and @@ accessors do not escape Lua keywords.

### ISSUE THREAD

**Issue by daelvn** [leafo/moonscript#384]
MoonScript supports syntax such as `t.for` and gets translated to `t["for"]`, it happens in table construction and other places as well. This however, isn't the case for indexes such as `@for` or `@@function`, which get translated into `self.for` and `self.__class.function` respectively, without escaping them.
The expected result is `self["for"]` and `self.__class["function"]`.

**Comment by leafo** [comment]
Fixed in 1ba34563f99e3e8a9d6685a0c84c3970a4885ede
