### ISSUE TITLE
Any method to use if statement in class method define?

### ISSUE THREAD

**Issue by zeroxer** [leafo/moonscript#445]
- Usage like this.
```
is_debug = true

class Person extends Thing
    if is_debug
        say_name: => print "Debug: Hello, I am #{@name}!"
    else
        say_name: => print "Release: Hello, I am #{@name}!"
```

**Comment by transmutrix** [comment]
Not leafo, but I assume the benefit you want is compile time evaluating that? AFAIK MoonScript doesn't do any compile-time evaluation of any kind.

A convention I use in several languages is to have a constant called Debug in each module and set it to true when I need debug output or extra checks turned on.

I dunno what your use case is, so I can't really speak to the effect on performance adding such ifs would have, but for the kind of things I tend to write, it is insignificant compared to other costs.

**Comment by zeroxer** [comment]
is_debug is just one case. I want to use this because I can use share some function code out of if/else and use the same function name with a clean code style. I dont want to use so many if/else in function. That was annoying when you have global is_debug(or something else), and have a lot debug code (or something else) to use. If support this usage, we can just remove the functions just for is_debug and keep the other no change.

Thanks for your reply.

**Comment by transmutrix** [comment]
Ah, I see what you mean.

Actually, I think you can have _almost_ exactly what you wanted. I tried this in the MoonScript playground [here](https://moonscript.org/compiler/), and it does work:

class Person
    say_name: if is_debug
      => "debug"
    else
      => "release"

test = Person!
test\say_name!

**Comment by zeroxer** [comment]
Cool!

I have tried one as fellow.
It seems  the single line of `=>` after `if is_debug` is a must. Is there any way to use `if is_debug =>` like `else =>` ?
```moonscript
is_debug = true

class Person
    say_name: if is_debug
      =>
        print "Debug: Hello, I am #{@name}!"
        print "Good Job"
    else =>
        print "Release: Hello, I am #{@name}!"
        print "Good Job"

    print_debug: if is_debug
      =>
        print "Print in debug"


with Person()
    .name = "MoonScript"
    \say_name!

with Person()
    .name = "DebugTest"
    \print_debug!
```
