### ISSUE TITLE
Moonscript as a self-contained library

### ISSUE THREAD

**Issue by SelectricSimian** [leafo/moonscript#58]
I'm not particularly familiar with the ins and outs of Luarocks, so I'm not sure what this modification would entail, but I'd _love_ to see Moonscript available as a self-contained Lua library (IE plug-and-play, not relying on LuaRocks)

**Comment by leafo** [comment]
There is a pure lua version of lpeg now, https://github.com/pygy/LuLPeg but it doesn't work with MoonScript.

Closing this though, feel free to open separate issue for any concerns.

**Comment by sherjilozair** [comment]
@leafo Does moonscript still not work with LuLPeg? Could you perhaps list the issues? I think it would be worth making moonscript work with LuLPeg.

**Comment by RyanSquared** [comment]
It should, and if not, it's a LuLPeg issue 😛

Seriously, though, I've heard lots of people having success using it with LuLPeg, so it should be fine.

**Comment by leafo** [comment]
I have no idea if it works or not, but it would be a good thing to add to the test matrix for travis
