### ISSUE TITLE
'loop' statement

### ISSUE THREAD

**Issue by SelectricSimian** [leafo/moonscript#60]
It's not a particularly important feature, considering it's just a simple alias to a two-word statement, but I'd love to have ```loop``` statements in moonscript instead of ```while true```.  It's more readable (```while true``` is more of a clever hack than anything else, and it certainly doesn't express intent), and its presence as an official language feature reminds programmers that when normal looping constructs have let them down, a good ol' infinite loop and ```break``` can often do the job better than anything else.

In addition, when followed by an expression on the same line, it could loop a set number of times.  Every time I use a ```for i = 1, times``` loop in my code, just to repeat something, I cringe a little at the unused variable.  A ```for _ = 1, times``` loop, which is the recommended way to handle an unused variable, looks even kludgier.  ```loop times``` would make a much more readable replacement, much like how ```!```, even though it only saves _one character_ of typing, makes those ugly ```()``` functions calls a thing of the past.

**Comment by leafo** [comment]
haven't seen any other interest in syntax like this, and at this point I'd rather not introduce a new keyword, so going to close. Feel free to re-open if you disagree.
