### ISSUE TITLE
Cannot run on Windows, get_opts fails

### ISSUE THREAD

**Issue by OlivierA** [leafo/moonscript#7]
I'm trying to use moonscript-0.1.0-1 installed with LuaRocks 2.0.4.1  on my Windows 7 computer.

"moonc" or "moon"  always fail with the following error, whatever the command-line arguments are:
```
lua: fatal error: `C:\LuaRocks/share/lua/5.1//alt_getopt.lua:75: attempt to get length of local 'arg' (a nil value)
stack traceback:
        C:\LuaRocks/share/lua/5.1//alt_getopt.lua:75: in function 'get_ordered_opts'
        C:\LuaRocks/share/lua/5.1//alt_getopt.lua:156: in function 'get_opts'
        [string "..."]:11: in main chunk'
```

**Comment by aristotll** [comment]
I download the binary from the main page, but it fails. Howerver, the newest binary form @leafo works.
