### ISSUE TITLE
No space allowed between key name and a colon in table literals

### ISSUE THREAD

**Issue by tophf** [leafo/moonscript#98]
The Moonscript [Language Guide](http://moonscript.org/reference/#table_comprehensions) says:
> assigning a value to a key in a table is done with : (instead of =).

But the following code fails to compile with a parse error:
```
x =
  key     : value
  longkey : value
```
Meanwhile '=' in lua
```
x = {
  key     = value,
  longkey = value
}
```
...has always been working with spaces.

**Comment by leafo** [comment]
the : must touch the key in the table literal to allow for other syntax

**Comment by buckle2000** [comment]
However, this should be documented and highlighted!
